server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true
---
spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8085
---
spring:
  profiles: docker
#  sleuth:
#    sampler:
#      probability: 1
#    web:
#      skipPattern: (^cleanup.*|.+favicon.*)

